###### To solve a puzzle, you are given an initial state and a goal state.
###### Target is to reach goal state from initial state using puzzle rules.
######  We can move blank tile only on left, right, up, and down
![Capture.JPG](attachment:Capture.JPG)

# Generate an intial state of NPuzzle

In [1]:
import numpy as np
import random
def get_state(N):    
    state = [item for item in range(N*N)]# [0,1,2,...,15]
    #print(state)
    random.shuffle(state)
    #print(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [2]:
get_state(3)

[[6 8 2]
 [1 4 0]
 [3 7 5]]


[6, 8, 2, 1, 4, 0, 3, 7, 5]

# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



![Capture.JPG](attachment:Capture.JPG)

In [3]:
def count_inversion(state):
    #arr = [i for i in arr if i !=0]
    print(state)
    inversion = []
    for i in range(len(state)):    
        count = 0
        for j in range(i+1,len(state)):        
            if state[i] > state[j]: 
                count = count + 1
        inversion.append(count)
    #print(inversion)
    return sum(inversion)

In [ ]:
s = get_state(4)
count_inversion(s)

[[13  7  4 12]
 [ 3  0  8 11]
 [ 6  5 15  2]
 [10 14  1  9]]
[13, 7, 4, 12, 3, 0, 8, 11, 6, 5, 15, 2, 10, 14, 1, 9]


62

# **Find blank row**

In [4]:
N =4

In [5]:
state = get_state(N)

[[ 7  1 12 15]
 [ 2  0 10  9]
 [ 5  6  3  4]
 [ 8 11 13 14]]


In [11]:
# find row position of the blank tile
# define here
def get_blank_row(state):
   
   for i in range(len(state)):
        if state[i]==0:
            m=i       
   return N-int((m/N))

In [7]:
R = get_blank_row(state) 
R

3

# Solvability Rules

In [12]:
I = count_inversion(state)
I

[2, 12, 11, 1, 10, 7, 13, 4, 14, 5, 3, 9, 8, 6, 15, 0]


62

In [13]:
# apply the rules to decide solvability
#  N, I, R
# define a method to return solvability (input S)
# return True if solvable or False if not
def isSolvable(initialState):
    if (N%2!=0 and I%2==0):
        return True
    elif (N%2==0 and R%2!=0 and I%2==0):
        return True
    elif (N%2==0 and R%2==0 and I%2!=0):
        return True
    else:
        return False
 
  


In [14]:
state = get_state(N) 
isSolvable(state)

[[13 11  4  8]
 [ 6  1 12 15]
 [ 3 10  9  5]
 [ 2  0 14  7]]


True